### PR TITLE
Added XP Multiplier Config

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Please add this as very much users will want to be able to change that

### CODE REVIEW

**Comment by Nacoran** [comment]
Not quite the same thing, but it would be great to be able to use something besides straight doubling.  How about an option to use a multiplier based on the fibonacci sequence?  Straight multiplication makes it so if you set the starting XP too low the first few levels are way to cheap.  If you set it too high the later levels are way to expensive.  Fibonacci would give you a nice curve.  (It's used in a lot of XP charts.)

**Comment by ThexXTURBOXx** [comment]
This sounds pretty great... I may add a Configuration to turn it on as well maybe 🤔

**Comment by bonii-xx** [comment]
TTL doesn't have a config to change the multiplier, since it's meant to softcap relatively quickly after a few levels. People would just use it to lower the modifier.. which is effectively the same as just handing people a few creative modifiers, which is what people should do in that case.

The fibonacci based multiplier sounds like an approach that'd keep the overall idea intact. If you provide a PR that allows to toggle between the two I'd accept it. Of course it'd have to start at 2.

**Comment by Nacoran** [comment]
10 Print "Beyond my programming skills"
20 Print "Request help"
30 Input X
40 If X=yes, Print "Smiley Face"
50 If X=no, goto 10
60 End

:P

**Comment by kyonkonyan** [comment]
I played this mod, and it impressed me a lot. But I wanna to play this mod with my friends which brought a problem here. I want to adjust this mod to match my sever, but I don't have compiling environment or tools now. Could you please change the "public float levelMultiplier = 2f;" in the file "src/main/java/slimeknights/toolleveling/config/ConfigFile.java" into "public float levelMultiplier = 1.25f;"  and send me a jar file which could supported by Minecraft 1.12.2 version. And here is my e-mail:kyonko_nyan@qq.com

**Comment by LumberWizard** [comment]
@bonii-xx you could set the minimum multiplier to 2. In my pack, I want to start it at 2 modifiers, cap it at 4, and have the 3rd modifier be really easy to get and the 4th one take a long time. I had to compile it myself to make it possible to set the multiplier to 100. I can make my own PR where the minimum is 2 if you want easier merging, or one with an option for the multiplier to keep growing after every level, according to the Fibonacci sequence or whatever.

**Comment by KnightMiner** [comment]
Closing as the repository is being archived. boni was always the main dev of this mod and he is inactive in modding these days.

**Pull request closed without merging**
